name: CI (PHP Lint Only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: PHP syntax lint (php -l)
        run: |
          echo "Procurando arquivos PHP para validar sintaxe..."
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 \
            | xargs -0 -n1 php -l

      - name: Code style (PHPCS PSR-12)
        run: |
          if [ -f "vendor/bin/phpcs" ]; then
            vendor/bin/phpcs --standard=PSR12 --extensions=php --ignore=vendor .
          else
            echo "PHPCS não encontrado. Adicione 'squizlabs/php_codesniffer' em require-dev no composer.json"
            exit 1
          fi
