name: CI (PHP Lint & Tests) + Deploy Hook
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2', extensions: mbstring, pdo, pdo_pgsql, coverage: none, tools: composer }
      - name: Install dependencies (composer)
        uses: php-actions/composer@v6
        with: { version: latest, php_version: "8.2", args: "--prefer-dist --no-interaction --no-progress" }
      - name: Lint (PHPCS) if available
        run: |
          if [ -x "vendor/bin/phpcs" ]; then vendor/bin/phpcs --standard=PSR12 src public || true; else echo "PHPCS não encontrado"; fi
      - name: Run tests (PHPUnit) if available
        run: |
          if [ -x "vendor/bin/phpunit" ]; then vendor/bin/phpunit --testdox || true; else echo "PHPUnit não encontrado"; fi
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook (if set)
        env: { RENDER_DEPLOY_HOOK_PROD: ${{ secrets.RENDER_DEPLOY_HOOK_PROD }} }
        run: |
          if [ -n "$RENDER_DEPLOY_HOOK_PROD" ]; then curl -fsS -X POST "$RENDER_DEPLOY_HOOK_PROD"; else echo "RENDER_DEPLOY_HOOK_PROD não definido."; fi
